# Generated by Django 5.1.7 on 2025-04-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='date_resp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='dem_filename',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='demande',
            name='document_resp',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='resp_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='resp_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
